name: Update PixInsight Repository

# Временно отключаем автозапуск
#on:
#  release:
#    types: [published]
#  workflow_dispatch:

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  update-repository:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Generate updates.xri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          python scripts/generate-xri.py
      
      - name: Commit and push updates.xri
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add docs/updates.xri
          git diff --staged --quiet || git commit -m "Update repository index for release ${{ github.event.release.tag_name }}"
          git push
